name: DrengrRunner

options:
  bundleIdPrefix: dev.drengr
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_ALLOWED: NO
    CODE_SIGN_IDENTITY: ""
    CODE_SIGN_REQUIRED: NO
    SUPPORTED_PLATFORMS: iphonesimulator
    SDKROOT: iphonesimulator
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

targets:
  DrengrRunner:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: DrengrRunner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.drengr.runner
        PRODUCT_NAME: DrengrRunner
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: DrengrRunner/Info.plist
        USES_XCTRUNNER: YES
        TEST_HOST: ""
        BUNDLE_LOADER: ""

schemes:
  DrengrRunner:
    build:
      targets:
        DrengrRunner: all
    test:
      targets:
        - DrengrRunner
